### ISSUE TITLE
Option to hide Example components from component list

### ISSUE THREAD

**Issue by qial** [headwirecom/themeclean-flex#142]
The preconfigured example components are useful when starting with and testing out peregrine, but if one is using it as the main CMS it seems like the default component list is way too cluttered.

**Comment by reusr1** [comment]
@qial one of the reasons for them to be there is for scaffolding pages quickly. makes it pretty easy to get a page up that looks about right and then fill in content. We should try to make sure we keep that functionality

**Comment by ehdatheadwire** [comment]
This might be deferred until we determine what to do with the component list in general. For now, I'll move it to the enhancements queue or a future parking lot.

**Comment by ehdatheadwire** [comment]
Moved to: https://github.com/peregrine-cms/enhancements/issues/69
