### ISSUE TITLE
Multilevel Navigation has issues on dark themes and will not link to pages with children

### ISSUE THREAD

**Issue by qial** [headwirecom/themeclean-flex#144]
Multilevel navigation will only link to a page if it does not have children. Not sure why it was done this way originally but it should link to all pages.

Additionally, there seem to be an issue with hardcoded color styles that don't work correctly on dark themes.

**Comment by qial** [comment]
This may be a problem with the theme itself. It is impossible to read the text on top of the "secondary background color" in the dark section of the theme.

![image](https://user-images.githubusercontent.com/1071825/89928839-40c25180-dbbd-11ea-9c87-2e2f4fdacc67.png)

You can then see the same issue when choosing the dark theme for the component:

![image](https://user-images.githubusercontent.com/1071825/89928898-5768a880-dbbd-11ea-98ac-c539872a96ba.png)

**Comment by smcgrath0** [comment]
PR #146

**Comment by ehdatheadwire** [comment]
Erin to close out on this after making sure there's another ticket in for the remaining issue of light over light display defaults.
