### ISSUE TITLE
content sharing

### ISSUE THREAD

**Issue by reusr1** [headwirecom/themeclean-flex#157]
**Please describe the problem.**
share the same content between multiple pages

**Describe the solution you'd like**
would be great to pull content from another page into the current page and effectively share it. This would help with building out the basic page structures as one could define the header and footer on one page and then pull it into multiple templates

**Additional context**
suggestion to build a reference component allowing to browse the page structure and pull a labelled content (content name) from that page

**Comment by reusr1** [comment]
updated the previous version of the reference component written by @bkheadwire from feature/reference-component - new implementation in issues/157 branch

**Comment by reusr1** [comment]
@Felix-Puetz could you please look at the inline edit related to this component? The way to use the component right now is as follows: 

go to for example the home page, select the hero, scroll all the way down in the dialog and give the hero a name (type in for example 'hero' into the content name field)

create a second page, add the reference component to the page, select the home page with the path field and enter 'hero' as the content name reference. Save the component. You should now see the hero from the home page on this page (but you should not be able to edit it and it would be great to take care of the console exceptions thrown in this use case)

**Comment by flx-sta** [comment]
@reusr1 looks good 

I've fixed the thrown errror in peregrine-cms branch `issues/494`
