### ISSUE TITLE
Property Groupings in Component Dialogs

### ISSUE THREAD

**Issue by qial** [headwirecom/themeclean-flex#160]
Currently, every component has a long list of properties to configure. Many of these fields are never used in day-to-day editing work. The dialog supports groups of fields through the `x-form-group` property in the component's model.json. 

We should make sure all the fields are grouped in ways that make sense for each component so that the dialog doesn't feel so cluttered.

**Proposal:** 
For a typical component, most fields can be broken down into three categories.

- Basic - The most necessary fields that define how a component works and almost always must be configured
- Styling - Extra formatting options, especially those options which are in the base component and are available on every component.
- Advanced - Configuration options that aren't immediately obvious and will rarely need to be used by an editor

Components can add further categories if they desire for more advanced components with many more configuration options.

**Comment by reusr1** [comment]
merged and tested in peregrine-cms/develop-sling12
