### ISSUE TITLE
Image width slider not allowing direct entry of number into box

### ISSUE THREAD

**Issue by ehdatheadwire** [headwirecom/themeclean-flex#172]
**Description**
Image width slider allows for image width to be adjusted via slider, but when entering number directly into size box, the following happens:

1. Number is not registered (as in, does not appear in box even though user is typing it)
2. Error message received that number is incorrect and either "cannot be zero" or is "greater than 100" even when it is not

**Steps to Reproduce**
1. Add a rich text component to page
2. Add an image
3. Attempt to adjust image width by adding numeric to box
4. See error message

**Expected Behavior**
* Box should work exactly as spacing box works for general component; e.g. number entered in box is registered same as slider

**Screenshots**
![Screen Shot 2020-11-25 at 1 16 42 PM](https://user-images.githubusercontent.com/51373617/100283134-c2967a80-2f21-11eb-8400-1dfcb95411a6.png)

**Screencast**
https://www.dropbox.com/s/0cq32tqfbi3sz0q/imagewidthissue.mp4?dl=0

**Desktop**
 - Chrome
 - Version 87.0.4280.67 (Official Build) (x86_64)
 - Mac OS Big Sur

**Comment by reusr1** [comment]
@ehdatheadwire is this still an issue and if so we need to track it in the peregrine-cms project as this is not an issue of themeclean-flex but the infrastructure peregrine provides

**Comment by ehdatheadwire** [comment]
this has been fixed!
