### ISSUE TITLE
Update images to modern formats

### ISSUE THREAD

**Issue by dna113p** [headwirecom/themeclean-flex#18]
https://developers.google.com/web/tools/lighthouse/audits/webp

**Comment by dna113p** [comment]
Modern formats are not yet well supported by all browsers. Will have to be implemented with fallbacks.

**Comment by ehdatheadwire** [comment]
Erin to close after creating new ticket in other repo.

**Comment by ehdatheadwire** [comment]
Moved to: https://github.com/peregrine-cms/enhancements/issues/71
