### ISSUE TITLE
Code Block Component - Feature Request

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/themeclean-flex#19]
Hi All,

I maintain a [technical blog](https://www.gastongonzalez.com/) and I'm in the process of migrating it off a hosted solution to Peregrine. A large portion of the content consists of code listings, sample files and command line instructions. Is there interest in the Peregrine community for a code block component with the following features?

* Syntax highlighting
* Line numbering
* Copy to clipboard

Up until this point, I have just been using a simple `<code>` element with basic CSS.

I discovered [Prism](https://prismjs.com/) as a potential client library for a robust code block component. Obviously, the solution that is used to implement this feature should aim for performance and be as lightweight as possible. 

Any feedback is welcome.

**Comment by GastonGonzalez** [comment]
We made some progress by injecting the Prism JS and CSS into a site template, however, the HTML code elements do not render correctly. This may be due to the way that Prism deals with changes made to the page by Peregrine. Invoking `Prism.highlightAll();` in Google's Web Developer Console temporarily illustrates what this integration could look like. We're looking into an approach for solving this problem.

**Comment by reusr1** [comment]
@GastonGonzalez @dna113p I added a basic code component in feature/code-component - please check it out. It hooks up to prism if prism is present, otherwise it outputs a regular <pre><code></code></pre> block.

**Comment by GastonGonzalez** [comment]
@reusr1 First, thank you for the initial PR. I was only able to perform limiting testing due to a number of blocking issues.

1. If a site already exists (i.e. gastongonzalez) that is based on themeclean-flex and a new build of themeclean-flex is deployed via Maven (`mvn clean install -P autoInstallPackage`), the site (gastongonzalez) will not have the component listed in the page view. This is not a themeclean-flex bug, but likely a Peregrine bug. Manually creating the component node in the existing site (i.e. /apps/gastongonzalez/components/code) with `sling:resourceSuperType=themecleanflex/components/code` will allow the code component to be seen on the page view as an available component. However, once the component is dropped on the page it is not visible (but is create as a node).

Given this issue, I opted to test the code component directly in the themeclean-flex. 

2. The code should not automatically set as `language-` as a prefix to the value of `language` property. The sample component defines `language-shell` as the default value. When the class is rendered on the page it is then rendered as `language-language-shell`. 

3. The `language` property should probably be renamed `class` as multiple classes can be defined to enable various Prism plugins. For example, this will define the language as Java and enable line numbers (`language-java line-numbers`).

4. The `text` property does not allow more than 209 characters to be defined when editing the component in the page view.

5. There were other styling issues, however, the above 4 issues made it difficult to test.

**Comment by reusr1** [comment]
@GastonGonzalez to make the component work in your site please also update the /etc/felibs/{tenant}/mapping.js file

I increased the character limit to 16k, added a new field classes and updated the sample.json for the initial component drop not to include language-

**Comment by GastonGonzalez** [comment]
@reusr1 - Thank you for the updates.

1. Adding `var cmpGastongonzalezComponentsCode = cmpThemecleanflexComponentsCode` to `/etc/felibs/gastongonzalez/mapping.js` resolved my issue. I can now edit the component on my tenant (gastongonzalez).
2. I like the approach of separating the language from the classes.
3. I can also confirm that the `text` property is large enough to handle large code blocks.

There are some issues with styling:
1. The theme color is not respected. I created my Prism JS/CSS with the `Tomorrow Night` theme.
2. Only syntax highlighting works. Even though I have the line number plugin enabled in my prism.css and prism.js and defined as a class, it does not work.

```
<pre>    <code class="language-ruby line-numbers">
...
```

I will send a screenshot and my prism.js/css via Slack.

```

**Comment by GastonGonzalez** [comment]
The last round of commits resolved the issues above. The following [PR](https://github.com/headwirecom/themeclean-flex/pull/24) has been created. The [readme](https://github.com/headwirecom/themeclean-flex/blob/feature/code-component/fragments/code/readme.md) has been updated with usage instructions for Prism.
