### ISSUE TITLE
Accordion: Image continues to display when media type is changed to video

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#39]
Steps to reproduce:
1. Add accordion component to page
2. Enable "Show Media"
3. Select "Image" for media type
4. Choose an image asset for the image source
![01-image](https://user-images.githubusercontent.com/5474176/61007818-b278fd80-a322-11e9-94e4-0303a0a1d276.png)
5. Change the media type to "Video"
![02-video](https://user-images.githubusercontent.com/5474176/61007825-b573ee00-a322-11e9-82ae-f165f281eb0e.png)

Expected result:
The image should not display with the "video" media type chosen

Actual result:
The image continues to appear even though a video with no source is selected

**Comment by dna113p** [comment]
Null value for src was causing an error that broke the rendering of videos. Added default values as empty strings.
