### ISSUE TITLE
Accordion: Icons display name instead of icon

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#40]
Steps to reproduce:
1. Add the accordion component
2. Enable "show media"
3. Choose "icon" as the media type
4. Select an icon
![03-iconmissing](https://user-images.githubusercontent.com/5474176/61008212-cec96a00-a323-11e9-8795-14f884b344b8.png)

Expected result:
The icon should appear on the page

Actual result:
The icon's name is displayed as text instead

**Comment by dna113p** [comment]
Since we have changed the way we include icons in our project, I have removed the icon option from the media component for now. Icons can still be included as an svg image.
