### ISSUE TITLE
Accordion: Asset browsers for media do not filter by type

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#41]
Steps to reproduce:
1. Add the accordion component
2. Enable "show media"
3. Choose an asset with the asset browser

Expected result:
Selectable assets should be limited to match the type chosen for media type, e.g. only images for the image media type.

Actual result:
Any kind of asset can be chosen.

**Comment by dna113p** [comment]
Blocked by https://github.com/headwirecom/peregrine-cms/issues/188
