### ISSUE TITLE
Cards: Cards per row lets you exceed max value

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#42]
Steps to reproduce:
1. Add cards component
2. Set the cards per row value to 7

Expected result:
Editor should stop you from choosing an out-of-range value

Actual result:
Out-of-range value is allowed and component turns into one big stretched card

**Comment by dna113p** [comment]
This is an issue that will have to be at least partially fixed in peregrine, as we aren't validating any of our inputs.

**Comment by dna113p** [comment]
Changed the number input to a range slider

**Comment by bkheadwire** [comment]
The slider does the trick for this particular issue. There is one slightly awkward thing I'm seeing now which is that when the slider is all the way to the right, a horizontal scroll bar shows up on the editor panel.

![01-sliderbar](https://user-images.githubusercontent.com/5474176/61500723-572db780-a981-11e9-96ec-96d4882eae47.PNG)

**Comment by reusr1** [comment]
@bkheadwire is this the case for all sliders? It is probably better to open a peregrine issue for this and close this issue out
