### ISSUE TITLE
Notes Component

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/themeclean-flex#43]
# Overview

In order to support the creation of technical articles within Peregrine, a component for dealing with notes, warnings, tips, etc. should be created.

The component shall support the following rendering views as a drop down selection:

- Note
- Tip
- Important
- Caution
- Warning

The Docbook publishing world uses the following rules to govern their use:
- Note: Information the user should be aware of, but is peripheral to the actual task being described.
- Tip: When you're giving a hint to make things easier or more productive for the reader.
- Important: When there is no danger of data loss, but you wish to make clear to the reader a consequence that isn't immediately obvious (e.g. when changing the font for one instance of a program also changes the default setting, and this isn't clear from the GUI.)
- Caution: A note of caution. Use this for example when the reader may lose easily recovered or replaceable information (e.g. user settings), or when they could cause data loss if they don't correctly follow the procedure being outlined.
- Warning: Use warning when data loss could occur if you follow the procedure being described.

## Example UI Styles

The following are a few examples of potential UI treatments. (I have no opinion on what these look like).

- https://docs.antora.org/antora/2.0/asciidoc/admonitions/
- https://www.madcapsoftware.com/blog/2017/08/17/css-tip-creating-styled-boxes-notes-warnings-examples-tips/
- https://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-alerts.php

FYI: @ehdatheadwire

**Comment by dna113p** [comment]
@GastonGonzalez I've added a note component to the develop branch

**Comment by reusr1** [comment]
@dna113p we should use the list provided by @GastonGonzalez and also make sure the width selection works

**Comment by reusr1** [comment]
@dna113p please verify all rich text component styles with a sample for this component

**Comment by GastonGonzalez** [comment]
@polished85, @dna113p and @reusr1 - This looks great. Apologies for the delay in testing.

![themeclean-flex-issue-43-verification](https://user-images.githubusercontent.com/1387966/62305251-69edc500-b434-11e9-8603-e02e809dbe0b.png)
