### ISSUE TITLE
Accordion: Text is cut off in mobile view

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#44]
Steps to reproduce:
1. Add accordion component to page
2. Change view to mobile

Expected result:
Accordion should stretch vertically to allow all text to display

Actual result:
Text is cut off within the accordion segments
![01-mobilecutoff](https://user-images.githubusercontent.com/5474176/61161643-9e1b3900-a4b9-11e9-98c8-1e213020ad67.PNG)

**Comment by dna113p** [comment]
Added a window resize handler to fix the height when going to mobile

**Comment by bkheadwire** [comment]
Confirmed fixed.
