### ISSUE TITLE
Accordion: Media "after content" option does not work in mobile/tablet widths

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#45]
Steps to reproduce:
1. Add an accordion component to the page
2. Enable "show media"
3. Choose an image file
4. Choose "after content" for media position
5. Change to mobile view

Expected result:
Media should display below the accordion segments

Actual result:
Media continues to appear above accordion
![02-mediaposition](https://user-images.githubusercontent.com/5474176/61161747-1aae1780-a4ba-11e9-8c5a-862bbe5650a7.PNG)

**Comment by qial** [comment]
This looks to still be an issue. Both "Before Content" and "After Content" in the mobile view shows the image above the accordian.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/1071825/89817646-61c36d80-dafd-11ea-96c2-28ca4e345302.png">

**Comment by qial** [comment]
This also appears to be an issue on the rich text component:
![image](https://user-images.githubusercontent.com/1071825/89933372-cea13b00-dbc3-11ea-857b-c42f9f2ca65f.png)

**Comment by MathisonProjects** [comment]
![image](https://user-images.githubusercontent.com/1110845/96152165-db971f00-0ed1-11eb-84d1-7c4505c5bd6e.png)
Looks like the issue is resolved.
