### ISSUE TITLE
Cards: "Cards per Row" behaves unexpectedly for tablet/mobile widths

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#46]
This may not be a bug so much as an issue of expectations. Maybe there should be a way to set different values for certain fields for each breakpoint?

Steps to reproduce:
1. Add the cards component to the page
2. Change to tablet view/mobile view

Expected result:
Number of cards matches cards per row value

Actual result:
Mobile view: only one card per row no matter what
Tablet view: 2 cards shown when CPR=3, 3 cards shown when CPR=4, etc.

**Comment by bkheadwire** [comment]
https://github.com/headwirecom/peregrine-cms/issues/140 made a ticket in peregrine for the general idea of different values for different views.

**Comment by dna113p** [comment]
Closing as I think this is more related to peregrine and the "experiences" feature needing to be further developed
