### ISSUE TITLE
Tabs: New tabs aren't showing up

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#47]
Steps to reproduce:
1. Add the tabs component to the page
2. Add a new tab
3. Fill out the tab title and test

Expected result:
Should see the new tab

Actual result:
Only 3 original tabs appear
![01-notab4](https://user-images.githubusercontent.com/5474176/61163024-71b6eb00-a4c0-11e9-9651-04f696e578aa.PNG)

**Comment by bkheadwire** [comment]
New tabs do appear after a refresh/leaving-returning to the page.

**Comment by dna113p** [comment]
@bkheadwire should be working now

**Comment by bkheadwire** [comment]
Confirmed fixed.
