### ISSUE TITLE
Tabs: Tabs wrap awkwardly at mobile width

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#48]
Steps to reproduce:
1. Add the tabs component to the page
2. Switch to mobile view

Expected result:
Tabs should all be on the same row

Actual result:
Third tab wraps onto a new line
![02-tabsmobile](https://user-images.githubusercontent.com/5474176/61163051-aaef5b00-a4c0-11e9-90d2-039a08961eb2.PNG)

**Comment by dna113p** [comment]
For the tab wrapping issue, I think this is the best that we can do when the tabs overflow the top line. I've decreased the margin on them to reduce this from happening.

Also fixed the issue with the text overflowing to the right margin in above image which was causing them to wrap earlier than necessary

**Comment by bkheadwire** [comment]
Definitely looks better now, good enough to close the issue.

I think it might be worth looking at how other existing sites deal with tabs for mobile widths. I've seen some where it turns from tabs into an accordion which worked decently.
