### ISSUE TITLE
Teaser: "Text Width" property slides text to the left regardless of alignment

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#59]
Steps to reproduce:
1. Add "teaser vertical" component to the page
2. Add text
3. Make sure "align content" is set to "Center"
4. Slide "text width" slider down below 100

Expected result:
Text should stay centered but become narrower to match the text width value

Actual result:
Text slides over to the left as the text width value decreases
![01-textwidth](https://user-images.githubusercontent.com/5474176/62086833-7d224a00-b214-11e9-96e8-218344357d57.PNG)

**Comment by reusr1** [comment]
works as expected :-)
