### ISSUE TITLE
Feature request: Multi-level link list component/nav

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/themeclean-flex#61]
![04-nav](https://user-images.githubusercontent.com/5474176/62088399-143dd080-b21a-11e9-926d-5b8b80a22b53.png)

We don't really have a nav bar component. Closest you can get is the static list of links in the header. It would be good to have a way to make generic lists of links that can go more than one level deep. Ideally we'd also have an option to generate that list from the content structure for creating navs.

**Comment by reusr1** [comment]
we should also allow for a property to easily exclude a page from the navigation

**Comment by qial** [comment]
This is now implemented in the "navigation" component. Hiding pages is fixed as of #135 when merged. Closing this issue.
