### ISSUE TITLE
Set good defaults for blank components

### ISSUE THREAD

**Issue by dna113p** [headwirecom/themeclean-flex#65]
- [x] accordion
- [x] cards
- [x] carousel
- [x] code
- [x] footer
- [x] header
- [x] mediablock
- [x] navigation
- [x] note
- [x] pagelist
- [x] pager
- [x] quote
- [x] richtext
- [x] simpletext
- [x] spacer
- [x] teaserhorizontal
- [x] teaservertical
- [x] tabs
- [x] media

**Comment by qial** [comment]
TODO: Will re-verify defaults
