### ISSUE TITLE
defer youtube video loading

### ISSUE THREAD

**Issue by reusr1** [headwirecom/themeclean-flex#74]
for performance reasons it would be better to lazy load youtube videos. See https://varvy.com/pagespeed/defer-videos.html for an example. Please also make sure the approach works if the video is changed while editing a page

**Comment by dna113p** [comment]
Added a simple lazy-load for videos > since the URL comes from the model we can just wait to bind it to the iframe until the component is mounted.

**Comment by reusr1** [comment]
this looks good, pages with videos have a high pagespeed score
