### ISSUE TITLE
v-lazy-load duplicated code

### ISSUE THREAD

**Issue by reusr1** [headwirecom/themeclean-flex#75]
due to the fact that multiple components use the z-lazy-load component for lazy loading images it would be better to define the component in the /apps/themecleanflex/components/page/renderer.html file to make it available to all components. Since we build each vue component into its own js file the code for the v-lazy-load component ends up living in each components js file that uses it and hence increases initial download time for a site.

**Comment by dna113p** [comment]
Moved the v-lazy code into an felib dependency and include it in the theme renderer.html

**Comment by qial** [comment]
Confirmed that v-lazy-image is in its own node module and referenced from renderer.html. Closing this issue.
