### ISSUE TITLE
mobile nav in header does not close on click

### ISSUE THREAD

**Issue by reusr1** [headwirecom/themeclean-flex#79]
**Describe the bug**
in mobile breakpoints the menu form the header component does not close when an item in the menu is clicked

**Comment by reusr1** [comment]
there is a synthetic event (pageRendered) that should be used to close the mobile navigation again after rendering: https://github.com/headwirecom/peregrine-cms/blob/411cc652a025f40c5f17f5a87936a8bdb7fba618/pagerenderer/vue/ui.apps/src/main/js/peregrineApp.js#L260-L264

**Comment by smcgrath0** [comment]
Don't see this issue, seems to be working for me. Send video?
