### ISSUE TITLE
Improve Samples for component library

### ISSUE THREAD

**Issue by dna113p** [headwirecom/themeclean-flex#9]
The component library could use improved samples so that you can quickly see what the different variations of each component can look like like.

- [x] Social Icons

**Comment by dna113p** [comment]
- [ ] Accordion dark
- [ ] Accordion w/ bg image
- [ ] Breadcrumb dark
- [ ] Cards dark
- [ ] Cards with custom color background
- [ ] 3/4/5 Card layouts
- [ ] Cards with background image
- [ ] Carousel full width
- [ ] Carousel w/o indicator
- [ ] Footer dark
- [ ] Header dark
- [ ] Full height/full width media blocks
- [ ] Page List w/root
- [ ] Pager dark
- [ ] Rich Text Dark
- [ ] Rich Text w/ better demonstrations of available editing capabilities
- [ ] Tabs w/ Title
- [ ] Tabs dark
- [ ] Tabs w/ Video
- [ ] Teaser Horizontal w/ bg image
- [ ] Teaser text left/right/center

**Comment by qial** [comment]
Will need to veryify and add Samples for new components, too.

**Comment by ehdatheadwire** [comment]
Closing for now due to length of open ticket and the fact that the interface has actually been updated since this time so some of this is moot.
