### ISSUE TITLE
Cards non-example's width is off

### ISSUE THREAD

**Issue by smcgrath0** [headwirecom/themeclean-flex#98]
**Describe the bug**
Wrong width for regular cards

**To Reproduce**
1. Drop cards component on page
2. add content to cards
3. add less cards than indicated in cards per row
4. See that there not the correct width 

**Expected behavior**

width of cards should be only indicated with cards per row, not based on content

**Screenshots**
has 4 cards per row, and cards only take up ~30% of the screen when its suppose to be 50%
![image](https://user-images.githubusercontent.com/49845255/81443655-a8827f80-912a-11ea-9588-f955116ebc28.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - OS: MacOS

**Comment by reusr1** [comment]
@smcgrath0 thank you :-) looks much better now
